name: React Web Notifications - publish to npm

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      - name: Extract package.json info
        id: extract_info
        run: |
          echo "::set-output name=tag_name::$(node -p 'require(\"./package.json\").version')"
          echo "::set-output name=release_name::$(node -p 'require(\"./package.json\").name')"
          echo "::set-output name=body::$(node -p 'require(\"./package.json\").description')"
        continue-on-error: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.extract_info.outputs.tag_name }}
          release_name: ${{ steps.extract_info.outputs.release_name }} ${{ steps.extract_info.outputs.tag_name }}
          body: ${{ steps.extract_info.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    needs: [release, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Create Tarball
        run: npm pack

  create-github-package:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npm pack

      - name: Create GitHub Package
        uses: actions/create-release@v1
        with:
          files: ./*.tgz
          release_name: ${{ steps.extract_info.outputs.release_name }} ${{ steps.extract_info.outputs.tag_name }}
          tag_name: ${{ steps.extract_info.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
